### PR TITLE
wined3d: Recognize GTX 1050 Ti card with NVIDIA driver.

### PR DESCRIPTION
**Pull request by kakra**
Signed-off-by: Kai Krakow <kai@kaishome.de>

### CODE REVIEW

**Comment by alesliehughes** [comment]
Why not send this patch upstream first?  Besides the space issue, that patch look fine.
+	CARD_NVIDIA_GEFORCE_GTX1050TI   = 0x1c82,
     CARD_NVIDIA_GEFORCE_GTX1060     = 0x1c03,

**Comment by kakra** [comment]
What is the best way to send it upstream? It looks like github PRs are mostly ignored, or at least only very rarely looked at...

**Comment by alesliehughes** [comment]
https://wiki.winehq.org/Submitting_Patches

**Comment by kakra** [comment]
Okay, submitted, although I'm not very comfortable with shuffling patches around mailing-lists. Closing.

**Pull request closed without merging**
